[backends]
  [backends.backend1]
  servers = ["server1", "server2"]

[servers]
  [servers.server1]
  url = "http://172.17.0.2:80"
  [servers.server2]
  url = "http://172.17.0.3:80"

[routes]
  [routes.route1]
  backends = ["backend1"]
    [routes.route1.rules.test_zenika]
    category = "Host"
    value = "test.zenika.fr"
