port = ":8001"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
domain = "toto.fr"
filename = "docker.tmpl"

[web]
address = ":8010"

#[file]
#filename = "træfik.toml"
#watch = true

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://172.17.0.2:80"
    [backends.backend1.servers.server2]
    url = "http://172.17.0.3:80"
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://172.17.0.2:80"

[routes]
  [routes.route1]
  backend = "backend2"
    [routes.route1.rules.test_zenika_1]
    category = "Host"
    value = "test.zenika.fr"
  [routes.route2]
  backend = "backend1"
    [routes.route2.rules.test_zenika_2]
    category = "Path"
    value = "/test"
